// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvFktXIGPTZ5O0zv6LgtoXEypUdm5BmzM',
    appId: '1:129947424619:web:d0ec0955af88656ccf5e2e',
    messagingSenderId: '129947424619',
    projectId: 'paymartpay',
    authDomain: 'paymartpay.firebaseapp.com',
    databaseURL: 'https://paymartpay-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paymartpay.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAam_n9-8I5sNL5-cHxKVM6X94QuBVvwRU',
    appId: '1:129947424619:android:4cb3a540204f3974cf5e2e',
    messagingSenderId: '129947424619',
    projectId: 'paymartpay',
    databaseURL: 'https://paymartpay-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paymartpay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeR4RjhZXqFqBYgK3FH3W0Rjf2ZhyrGFk',
    appId: '1:129947424619:ios:4d60275f4f756fdecf5e2e',
    messagingSenderId: '129947424619',
    projectId: 'paymartpay',
    databaseURL: 'https://paymartpay-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paymartpay.appspot.com',
    iosClientId: '129947424619-istelkgaajphjn8kbeid3gujrs9aorrm.apps.googleusercontent.com',
    iosBundleId: 'com.paymart.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeR4RjhZXqFqBYgK3FH3W0Rjf2ZhyrGFk',
    appId: '1:129947424619:ios:4d60275f4f756fdecf5e2e',
    messagingSenderId: '129947424619',
    projectId: 'paymartpay',
    databaseURL: 'https://paymartpay-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'paymartpay.appspot.com',
    iosClientId: '129947424619-istelkgaajphjn8kbeid3gujrs9aorrm.apps.googleusercontent.com',
    iosBundleId: 'com.paymart.app',
  );
}
